#!/bin/bash

SUBSTITUTIONS+=('SSL_ERROR_[a-zA-Z0-9_]*')
SUBSTITUTIONS+=('SSL_MODE_[a-zA-Z0-9_]*')
SUBSTITUTIONS+=('SSL_AD_[a-zA-Z0-9_]*')
SUBSTITUTIONS+=('DTLS1_VERSION_MAJOR')
SUBSTITUTIONS+=('SSL3_VERSION_MAJOR')
SUBSTITUTIONS+=('SSL3_VERSION')
SUBSTITUTIONS+=('TLS1_VERSION')
SUBSTITUTIONS+=('TLS1_1_VERSION')
SUBSTITUTIONS+=('TLS1_2_VERSION')
SUBSTITUTIONS+=('TLS1_3_VERSION')
SUBSTITUTIONS+=('DTLS1_VERSION')
SUBSTITUTIONS+=('DTLS1_2_VERSION')
SUBSTITUTIONS+=('SSL_R_[a-zA-Z0-9_]*')
SUBSTITUTIONS+=('SSL_TLSEXT_ERR_[A-Z_]*')
SUBSTITUTIONS+=('SSL_SESS_CACHE_[A-Z_]*')
SUBSTITUTIONS+=('OPENSSL_NPN_[A-Z_]*')
SUBSTITUTIONS+=('SSL_OP_[a-zA-Z0-9_]*')

EXPRE='s|^//[ \t]#[ \t]*define[ \t]*[^a-zA-Z0-9_]\('
EXPOST='\)[^a-zA-Z0-9_].*$|#ifdef ossl_\1\n#define \1 ossl_\1\n#endif|'

for SUBSTITUTION in "${SUBSTITUTIONS[@]}"
do
	sed -i -e "${EXPRE}${SUBSTITUTION}${EXPOST}" "$1"
done
