name: OpenSSL testing

permissions:
  contents: read

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  openssl:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    permissions:
      contents: read
      packages: read
    if: >-
      ${{ github.repository == 'envoyproxy/envoy-openssl' }}
    steps:
    - name: Free disk space
      uses: envoyproxy/toolshed/gh-actions/diskspace@actions-v0.3.23
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - run: |
        ./ci/run_envoy_docker.sh './ci/do_ci.sh gcc //test/...'
      env:
        BAZEL_BUILD_EXTRA_OPTIONS: >-
          --config=remote-envoy-engflow
          --config=bes-envoy-engflow
          --config=remote-ci
        ENVOY_RBE: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ENVOY_BUILD_IMAGE: quay.io/jwendell/envoy-build-ubuntu:openssl-f4a881a1205e8e6db1a57162faf3df7aed88eae8
